### PR TITLE
update phpunit namespaces

### PR DESCRIPTION
**Pull request by prisis**
Now it works with phpunit 6 too :)

### CODE REVIEW

**Comment by shadowhand** [comment]
PHPUnit 6 requires PHP 7. This is not the right solution.

**Comment by prisis** [comment]
But composer requites phpunit 5.7 with the new namespaces

**Comment by Nyholm** [comment]
PHPunit 6.0 has the new namespaces.

**Comment by prisis** [comment]
my mistake.... sorry how about a class exists?

**Comment by prisis** [comment]
I was right, the class exists on phpunit 5.7 https://github.com/sebastianbergmann/phpunit/blob/5.7/src/ForwardCompatibility/TestCase.php

**Comment by shadowhand** [comment]
@prisis but why would we use a class that is essentially an alias? I'd rather do a full switch to PHP7 when the time comes than switch this now.

**Comment by prisis** [comment]
If someone using phpunit6 on php7 he can't add this package because of a old namespace...

**Comment by shadowhand** [comment]
I don't understand your argument, `phpunit` is a `require-dev` dependency. PHPUnit 5.7 is completely usable on PHP 7.

**Comment by prisis** [comment]
Yes, you right, that phpunit 5.7 works on php7 too, but if someone using phpunit 6 for his tests, he can't use this library.

**Pull request closed without merging**
