### PR TITLE
fixed some oversights from #48

### PR DESCRIPTION
**Pull request by codemasher**
You might want to merge this before tagging 2.0

### CODE REVIEW

**Review by shadowhand — APPROVED** [review]
Thanks!

**Comment by codemasher** [comment]
Hi uh can we please have a new version tagged finally?

**Comment by shadowhand** [comment]
Version 2.1.0 tagged.

**Comment by shadowhand** [comment]
Also, please check the attitude. This is an open source project and I don't owe you anything. Please be respectful.

**Comment by codemasher** [comment]
I spent several hours of work in this PR/project and waited literal years to finally get it merged and you went radio silent immediately after it instead of tagging a release countless people were waiting for. But it's my "attitude" for asking. Right, got it.

**Comment by shadowhand** [comment]
@codemasher I'm going to break this down, since it didn't sink in the first time around...

> I spent several hours of work in this PR/project

Your work is appreciated. I have also spent hours of work on this project, including the multitude of hours I spent working with PHP-FIG to get PSR-17 published.

> and waited literal years to finally get it merged

Again, this open source. I am not paid to do this. The implication you are making is that you are _entitled_ to something from me. Unless you are going to support this project by paying me for my time, I owe you _absolutely nothing_.

> and you went radio silent immediately after it

Factually untrue. Version 2.0.0 was tagged after #47, and (AFAICT) there are no _functional_ changes between [2.0 and 2.1](https://github.com/http-interop/http-factory-tests/compare/2.0.0..2.1.0), so there was little urgency on my part. (And again, see above.)

> instead of tagging a release countless people were waiting for.

No one else has commented or reacted to indicate they were waiting for these changes to be tagged. So the number of people waiting is very countable: one.

> But it's my "attitude" for asking. Right, got it.

It has nothing to do with _asking_ and everything to do with _how you asked_. When you ask in an entitled, petulant way I am absolutely going to call that out. And rather than apologizing, or thanking me, or even _saying nothing at all_, you doubled down with this childish response. 🙄

Please be more mindful of how you talk to others who are _giving_ their time for your benefit.

**Pull request merged**
