### PR TITLE
Allow installing on PHP 8.

### PR DESCRIPTION
**Pull request by ADmad**

### CODE REVIEW

**Review by shadowhand — APPROVED** [review]

**Comment by shadowhand** [comment]
Thanks!

**Comment by ADmad** [comment]
Welcome, can we have a new release please.

**Comment by tuupola** [comment]
Waiting for release.

**Comment by ADmad** [comment]
@tuupola `0.7.0` has already been released with this change.

**Comment by tuupola** [comment]
Gotcha. Although upgrading from 0.5.0 to 0.7.0 my Travis builds start failing. Am I missing something obvious?

```
There were 4 errors:

1) Interop\Http\Factory\StreamFactoryTest::testCreateStreamFromNonExistingFile
fopen(/tmp/http_factory_tests_kGlxRj): failed to open stream: No such file or directory
/home/travis/build/tuupola/http-factory/src/StreamFactory.php:72
/home/travis/build/tuupola/http-factory/vendor/http-interop/http-factory-tests/test/StreamFactoryTestCase.php:89

2) Interop\Http\Factory\StreamFactoryTest::testCreateStreamFromInvalidFileName
fopen(): Filename cannot be empty
/home/travis/build/tuupola/http-factory/src/StreamFactory.php:72
/home/travis/build/tuupola/http-factory/vendor/http-interop/http-factory-tests/test/StreamFactoryTestCase.php:95
3) Interop\Http\Factory\StreamFactoryTest::testCreateStreamFromFileWithNoMode
fopen(/tmp/http_factory_tests_XbnQuC): failed to open stream: Success
/home/travis/build/tuupola/http-factory/src/StreamFactory.php:72
/home/travis/build/tuupola/http-factory/vendor/http-interop/http-factory-tests/test/StreamFactoryTestCase.php:124

4) Interop\Http\Factory\StreamFactoryTest::testCreateStreamFromFileWithInvalidMode
fopen(/tmp/http_factory_tests_iWFc3n): failed to open stream: Success
/home/travis/build/tuupola/http-factory/src/StreamFactory.php:72
/home/travis/build/tuupola/http-factory/vendor/http-interop/http-factory-tests/test/StreamFactoryTestCase.php:132
```

**Comment by ADmad** [comment]
No idea about that. I don't use this package directly myself, I submitted the patch just because it's a dependency of `laminas/diactoros`.

**Comment by tuupola** [comment]
Oops. Accidentally deleted the previous comment. In any case I will dig a bit deeper why Travis builds start to fail after upgradeing. Thanks!

**Comment by shadowhand** [comment]
@tuupola probably because of the changes made in #42?

**Comment by tuupola** [comment]
@shadowhand That's it. Thanks!

**Pull request merged**
